name: Build

on: [push, pull_request]

jobs:
  build:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}



    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install
        run: yarn --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production


